ボウリングのスコアを途中段階でも計算できる機能追加
kitazawasyogo/bowling pull request #10
Opened 2023-01-25 02:52 UTC by kitazawasyogo

@nabemasamasa　@Takatatsu9

ボウリングのスコアを途中段階でも計算できる機能を追加しました。

不足している部分、よりよい書き方などがありましたら教えて頂きたいです。
お忙しいところ恐れ入りますがレビューお願いいたします。

2023-01-25 03:58 UTC, kitazawasyogo commented
Pushした後ですが修正が必要な個所を見つけ修正しました。

f29a845　こちらのコミットまでレビューお願いいたします。

2023-01-25 03:58 UTC, nabemasamasa commented on Bowling.Test/BowlingTest.vb
> - feat/array-length-check
[Q] ?????? なんで #9 で消えたはずのコードが復活してるんですか???
#9 マージしたなら、マージした後のmasterがGitHub上の最新masterのはずなのに、消したはずのコードが復活してるし……
https://github.com/kitazawasyogo/bowling/blob/6f8777f570527c2b4b07beb2684a2f784626c947/Bowling.Test/BowlingTest.vb#L22

もしかして、ローカルの古いmasterでgit push --force origin masterしませんでした？

2023-01-25 04:14 UTC, kitazawasyogo commented on Bowling.Test/BowlingTest.vb
> - feat/array-length-check
> もしかして、ローカルの古いmasterでgit push --force origin masterしませんでした？


失礼いたしました。ローカルのmasterが古い状態でした。
こちらのPRのCloseとブランチの削除を行い、ローカルのmasterを正しい状態にしてからPR立てなおさせていただきます。

2023-01-25 04:53 UTC, Takatatsu9 commented
え？もしかしてGitHubのMergeボタンじゃなくてGit BashからMergeしてた…？

2023-01-25 05:24 UTC, kitazawasyogo commented
> え？もしかしてGitHubのMergeボタンじゃなくてGit BashからMergeしてた…？

MergeはGitHubのMergeボタンで行っていました。

①ローカルのプルマージをし忘れ、ローカルのmasterが古い状態でmasterからブランチを作成してしまった
②プルマージし忘れていた後の対応としてgit push -f origin master をしてしまった
事が原因です。

2023-01-25 05:32 UTC, Takatatsu9 commented
なるほど、了解です

2023-01-25 05:45 UTC, kitazawasyogo commented
ローカルのmasterを最新の状態にしてから機能追加を強制プッシュしました。

155a435 02f371c こちらのふたつのコミットのレビューお願いいたします。

2023-01-25 07:58 UTC, nabemasamasa commented
[Q] これ、どうなりました？

> Bowlメソッドを追加し、Scoreは呼ばれた時点でのBowlメソッド引数の合計値を返せるようにせよ

2023-01-26 02:40 UTC, Takatatsu9 reviewed
Done

2023-01-26 02:40 UTC, Takatatsu9 commented on Bowling/Bowling.vb
> +    Public Shared RecordEveryThrow As Integer
[Q] `Public Shared`である必要はありますか？

2023-01-26 02:40 UTC, Takatatsu9 commented on Bowling/Bowling.vb
> +        Bowling.RecordEveryThrow = oneThrow
[IMO] このメソッドでやってることがPublic Shared変数に入れるのが全てなら
このメソッドの存在価値自体無いんですけど・・・

2023-01-26 05:53 UTC, kitazawasyogo commented on Bowling/Bowling.vb
> +    Public Shared RecordEveryThrow As Integer
Public 　Sharedである必要はありませんでした。
Public 変数　の形に修正します。

2023-01-26 06:16 UTC, Takatatsu9 commented on Bowling/Bowling.vb
> +    Public Shared RecordEveryThrow As Integer
[Q] なぜ`Public Shared`である必要はなかったんですか？

2023-01-26 07:15 UTC, nabemasamasa commented
そろそろ質問してから一日が経つのでリマインドです。
https://github.com/kitazawasyogo/bowling/pull/10#issuecomment-1403224322

2023-01-26 07:46 UTC, Takatatsu9 commented on Bowling/Bowling.vb
> +        Bowling.RecordEveryThrow = oneThrow
`Bowling.RecordEveryThrow = value`と`Bowl(value)`が全く同じ挙動なら片方要らないでしょ⇒存在価値が無い
という話をしました

2023-01-27 00:56 UTC, kitazawasyogo commented on Bowling/Bowling.vb
> +    Public Shared RecordEveryThrow As Integer
`Public Shared`にしてしまうとクラスのインスタンスが幾つ生成されても常に一つしか場所を確保しない為、
テストごとにクラスのインスタンスを作成しても毎回同じレーンのスコアを計算することになってしまうので間違いだと思います。

2023-01-27 00:56 UTC, kitazawasyogo commented
https://github.com/kitazawasyogo/bowling/pull/10#issuecomment-1403224322
Issueの指示に沿えるように修正します。
・クラス変数をListに変更し、Bowlメソッド引数を代入していく
・Scoreメソッドの引数をクラス変数のListの値に変更

2023-01-27 01:00 UTC, kitazawasyogo commented
Issueの指示に沿えるように修正しました。

お忙しいところ恐れ入りますがレビューお願いいたします。

2023-01-27 01:32 UTC, nabemasamasa submitted a review, later dismissed
NG。コミットのルール違反。

2023-01-27 01:32 UTC, nabemasamasa commented on Bowling/Bowling.vb
> +    Public Function Score(pins As List(Of Integer)) As Integer
[Q] `RecordEveryThrow`って、Publicである必要ありますか？

2023-01-27 01:32 UTC, nabemasamasa commented on Bowling.Test/BowlingTest.vb
> +        Dim actual As Integer = bowlingScore.Score(bowlingScore.RecordEveryThrow)
[Q] なんで「ScoreメソッドもSharedである『必要がない』」んですか？

2023-01-27 01:32 UTC, nabemasamasa commented on Bowling/Bowling.vb
> +    Public RecordEveryThrow As New List(Of Integer)
> 一投ごとの記録を持たせられるようにするためにリストを変更

[Q] リストに変更と言いつつ、Sharedを外して動作が変わっていますが、それのWhyはなんですか？
あと、このコミットでコンパイルできますか？ビルドは動きますか？
コミットをする前に確認しましたか？

2023-01-27 01:32 UTC, nabemasamasa commented on Bowling/Bowling.vb
> +    ''' 一投で倒したピンの数をクラス変数のリストに代入
[Q] 例えば、何も知らない人がbowlingのBowlメソッドを使おうとしたとき、このコメントが表示されるんですけど「クラス変数のリストに代入」ってなんですか？

2023-01-27 01:32 UTC, nabemasamasa commented on Bowling/Bowling.vb
> +        RecordEveryThrow.Add(oneThrow)
コメントの「代入」なんだけど「代入」してない。Addは代入じゃない。

2023-01-27 01:32 UTC, nabemasamasa commented on Bowling.Test/BowlingTest.vb
> -        Dim pinsArray As Integer() = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
[Q] 「BowlingクラスのTestが行えるように」って事は、それまでテスト動いてなかったってことですか？
Gitのコミットのルールで、「エラーが起こらないコミットにすること」とあるのですが、ルール違反ってことですか？
https://github.com/daniel-software-tokyo/knowledge/blob/master/git/Git.beginner.md#%E3%82%B3%E3%83%9F%E3%83%83%E3%83%88%E3%81%AE%E3%83%AB%E3%83%BC%E3%83%AB

2023-01-27 01:35 UTC, Takatatsu9 commented on Bowling/Bowling.vb
> +    Public Shared RecordEveryThrow As Integer
それ私が昨日説明したことそのまま言ってるだけですよね。
それを知る前に @kitazawasyogo は必要ないと判断したわけですが、
それはなぜかを知りたかったんですが・・・。

2023-01-27 04:42 UTC, kitazawasyogo commented on Bowling.Test/BowlingTest.vb
> +        Dim actual As Integer = bowlingScore.Score(bowlingScore.RecordEveryThrow)
テストごとにクラスのインスタンスを生成してScoreメソッドを呼び出したいのでScoreメソッドもSharedにすると間違いだと考えています。

2023-01-27 04:47 UTC, kitazawasyogo commented on Bowling.Test/BowlingTest.vb
> -        Dim pinsArray As Integer() = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
その通りです。ルール違反になります。

内容ごとにコミットを分ける事に集中し、Gitのコミットのルールで「エラーが起こらないコミットにすること」を確認していませんでした。
コミットのルール違反にならないようにコミットしなおさせていただきます。

2023-01-27 04:54 UTC, kitazawasyogo commented on Bowling/Bowling.vb
> +    Public Shared RecordEveryThrow As Integer
Sharedについて調べて`Public Shared`との場合と`Public 変数`の場合を書き換えて両方試し、`Public 変数`でもTest結果がでたからです。

Sharedについて調べてなんとなく理解していましたが昨日説明して頂いた時にしっかり理解できたので説明して頂いたことを返答としてそのまま言ってしまいました。

2023-01-27 04:59 UTC, kitazawasyogo commented on Bowling/Bowling.vb
> +    Public RecordEveryThrow As New List(Of Integer)
テストごとにクラスのインスタンスを生成し、テストごとのRecordEveryThrow を使用できるようにするためです。

> あと、このコミットでコンパイルできますか？ビルドは動きますか？
> コミットをする前に確認しましたか？

確認しておらず、エラーの起こるコミットになってしまいました。
エラーの起こらない、内容ごとに分けられた役割が単一で明確なコミットに修正いたします。

2023-01-27 04:59 UTC, kitazawasyogo commented on Bowling/Bowling.vb
> +    ''' 一投で倒したピンの数をクラス変数のリストに代入
理解しやすいコメントをに変更いたします。

`一投で倒したピンの数を記録するリストに追加`

2023-01-27 05:11 UTC, nabemasamasa commented on Bowling.Test/BowlingTest.vb
> +        Dim actual As Integer = bowlingScore.Score(bowlingScore.RecordEveryThrow)
インスタンスメソッドにしたいならその通りでSharedを外さないといけない。
けど、なんでインスタンス分けたいんだっけ？
それが本当のWhyだと思う。

2023-01-27 05:15 UTC, Takatatsu9 reviewed
Done

2023-01-27 05:15 UTC, Takatatsu9 commented on Bowling/Bowling.vb
> +    Public RecordEveryThrow As New List(Of Integer)
[nits] public変数ってクラス外でも読み書き自由にできちゃうから
知らないところで勝手に書き換えられたりする恐れもあってあまり使いたくない・・・。

もちろん、読み込み書き込みフルアクセスしたいって場合があるならそれでもいいけど、
そういうパターンはList型では稀。

2023-01-27 05:15 UTC, Takatatsu9 commented on Bowling/Bowling.vb
> +    ''' 一投で倒したピンの数をクラス変数のリストに代入
どうかな、メソッドのコメントって「メソッドがやってくれる機能を紹介する」ものであって
「メソッドの中にあるロジックの解説」じゃないと思うんですよ。
だから`一投で倒したピンの数を記録する`だけで十分かなと。

2023-01-27 05:15 UTC, nabemasamasa commented on Bowling/Bowling.vb
> +    Public RecordEveryThrow As New List(Of Integer)
> テストごとにクラスのインスタンスを生成し、

これがShared外すときのWhyだし、「一投ごとの記録を持たせる為にリストを変更」のWhyとは無関係だと思う。

…ところで、「リスト **を** 変更」じゃなくて「リスト **に** 変更」だと思う。Typoはまぁ誰にでもあることだけど。

2023-01-27 06:19 UTC, kitazawasyogo commented on Bowling/Bowling.vb
> +    Public Function Score(pins As List(Of Integer)) As Integer
こちらの質問ですが、自分で回答出せませんでした。
https://github.com/kitazawasyogo/bowling/pull/10#discussion_r1088589037
　頂いたコメントにある通りです。

前にレビューして頂いたように、予期せぬ事故が起きないようスコープが狭められないかチェックするよう心がけます。

2023-01-27 06:20 UTC, kitazawasyogo commented on Bowling.Test/BowlingTest.vb
> +        Dim actual As Integer = bowlingScore.Score(bowlingScore.RecordEveryThrow)
インスタンス分けることで、途中経過ごとの合計値を求められるからです。

2023-01-27 07:21 UTC, kitazawasyogo commented on Bowling/Bowling.vb
> +    Public RecordEveryThrow As New List(Of Integer)
コメントありがとうございます。
Public 変数である必要がない場合は使用しない事と理由について理解出来ました。


テストでScoreメソッドの引数に使用したいのでPublic 変数にしていましたが、Public 変数を使用しない場合の方法が分かっていません。
よろしければPublic 変数を使用しない場合の方法を教えて頂きたいです。

2023-01-27 07:31 UTC, Takatatsu9 commented on Bowling/Bowling.vb
> +    Public RecordEveryThrow As New List(Of Integer)
Getプロパティ、あるいは取得するためのメソッドを用意するのがいいです。
List型はそのまま渡すと中身を変更できてしまうので、配列に変換することでそれが回避できます。

- Getプロパティ
    - そのまま返すのが基本的な使い方なので、Integer型やString型など
    プリミティブ型（型名が青くなるやつ）に適してる
    - それ以外の使い方もあるけど、ここでは省略
- Getメソッド
    - ロジックで値を加工して返す場合とかに使う
    -  内部で持ってるList型値を配列変換して返したい場合とかは主にこっち

2023-01-27 07:41 UTC, nabemasamasa commented on Bowling.Test/BowlingTest.vb
> +        Dim actual As Integer = bowlingScore.Score(bowlingScore.RecordEveryThrow)
「前の結果を残さず、新しくテストをする為『Sharedである必要がない』」ことを口頭で説明受け理解しました。

2023-01-27 07:51 UTC, nabemasamasa commented on Bowling/Bowling.vb
> +    Public RecordEveryThrow As New List(Of Integer)
ごめん。
口頭で「そもそもScoreに引数って必須なの？課題3ではScoreは呼ばれた時点での合計値を返せとしか書いてないよ？」って会話して、クラス変数の合計値をScoreが直接返す方向になりました。

2023-01-27 07:53 UTC, Takatatsu9 commented on Bowling/Bowling.vb
> +    Public Function Score(pins As List(Of Integer)) As Integer
<img width="500" alt="スクリーンショット 2023-01-27 16 50 50" src="https://user-images.githubusercontent.com/50448373/215035502-c96a735e-1c57-4311-b8f7-da572264d2a2.png">

Publicである必要があるかではなく、
Publicでないといけない理由で考えたら答えは出ませんか？

2023-01-30 01:05 UTC, kitazawasyogo commented
レビューありがとうございます。

ご指摘頂いた部分の修正とエラーの起こらないコミットに修正し、強制プッシュしました。
お忙しいところ恐れ入りますがレビューお願いいたします。

2023-01-30 01:41 UTC, Takatatsu9 requested changes
Done

2023-01-30 01:41 UTC, Takatatsu9 commented on Bowling/Bowling.vb
> +    Private ScoreList As New List(Of Integer)
[MUST] Public変数が大文字始まりで書かなきゃいけないように、
Private変数にもそういうような命名ルールがあるんですけど

2023-01-30 01:41 UTC, Takatatsu9 commented on Bowling.Test/BowlingTest.vb
> -        Dim pinsArray As Integer() = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21}
> Scoreメソッドの引数を配列からクラス変数のリストに変更し、引数のテストが不要になる為削除

[IMO] これWhyじゃなくてWhatですね

2023-01-30 01:41 UTC, Takatatsu9 commented on Bowling/Bowling.vb
> -    ''' <param name="pins">倒したピンの数の配列</param>
> 前の結果を残さず新しいテストをする為、Sharedを外し引数を一投ごとの記録のリストに変更

[Q] 「前の結果」って何を指してますか？

2023-01-30 02:06 UTC, kitazawasyogo commented on Bowling.Test/BowlingTest.vb
> -        Dim pinsArray As Integer() = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21}
`引数のテストが不要になる為削除`だけで伝えられるかと思いますので変更いたします。

2023-01-30 02:07 UTC, kitazawasyogo commented on Bowling/Bowling.vb
> -    ''' <param name="pins">倒したピンの数の配列</param>
前のテスト結果です。

`前のテスト結果を残さず新しいテストをする為、Sharedを外し引数を一投ごとの記録のリストに変更`に変更いたします。

2023-01-30 02:24 UTC, Takatatsu9 commented on Bowling.Test/BowlingTest.vb
> -        Dim pinsArray As Integer() = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21}
いいと思います。
それはそれとして、そういうWhyであるなら、そのテストで使ってるメソッドか何かの
引数を削除するコミット？引数テストが不要になったコミットと一緒にしてしまっていいと思います。

2023-01-30 02:28 UTC, Takatatsu9 commented on Bowling.Test/BowlingTest.vb
> +        Dim actual As Integer = bowlingScore.Score()
[Q] あれ？`Scoreメソッドの引数を配列からクラス変数のリストに変更し～` 70b28e2 の
コミットの段階ではまだ`Score`メソッドは引数が必要なはずだと思うんですけど。
このコミットをチェックアウトして動かしたらテストちゃんと動きますか？

2023-01-30 02:52 UTC, kitazawasyogo commented on Bowling.Test/BowlingTest.vb
> -        Dim pinsArray As Integer() = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21}
[25be98e](https://github.com/kitazawasyogo/bowling/pull/10/commits/25be98e05f9af43985da283d2738268c963857ec)と[70b28e2](https://github.com/kitazawasyogo/bowling/pull/10/commits/70b28e25be7faa664ac8b0cb4ae8d92fdfd7702e)の二つのコミットを一つにまとめ、
`前の結果を残さず新しいテストをする為、Sharedを外し引数を一投ごとの記録のリストに変更`　にします。

同じように「メソッドの変更」と「変更したメソッドのテストを削除」するコミットに分けている[09f8c99](https://github.com/kitazawasyogo/bowling/pull/10/commits/09f8c9900274c5ef60a40153e1fd8e3c9fb7c4af)と[0ce8e8c](https://github.com/kitazawasyogo/bowling/pull/10/commits/0ce8e8c812515aa27c6ec963d013496194ac41b3)も`テストごとにクラスのインスタンスを作成し一投ごとの記録を持たせる為にリストに変更`で一つにまとめます。

2023-01-30 04:41 UTC, kitazawasyogo commented on Bowling.Test/BowlingTest.vb
> +        Dim actual As Integer = bowlingScore.Score()
https://github.com/kitazawasyogo/bowling/commit/70b28e25be7faa664ac8b0cb4ae8d92fdfd7702e
コミットにチェックアウトして確認した所、エラーが起こるコミットになってしまっていました。

https://github.com/kitazawasyogo/bowling/pull/10#discussion_r1090123399
頂いたコメントの様に二つのコミットをまとめ、エラーの起こらないコミットに修正いたします。

2023-01-30 04:47 UTC, kitazawasyogo commented
レビューありがとうございます。

ご指摘頂いた部分の修正を行い強制プッシュしました。
お忙しいところ恐れ入りますがレビューお願いいたします。

2023-01-30 04:50 UTC, Takatatsu9 reviewed
Done

2023-01-30 04:50 UTC, Takatatsu9 commented on Bowling.Test/BowlingTest.vb
> +    <Test()> Public Sub 二投目に九ピン倒した段階のスコアを計算()
> 前のテスト結果を残さず新しいテストをする為、Sharedを外し引数を一投ごとの記録のリストに変更
前の結果を残さず新しいテストをする為、Sharedを外し引数を一投ごとの記録のリストに変更

[Q] なんで同じようなこと2回書いてあるんですか？

2023-01-30 04:53 UTC, Takatatsu9 commented on Bowling.Test/BowlingTest.vb
> +        Dim actual As Integer = bowlingScore.Score()
次から全コミット単位もで正常に動作するものをコミットするようにしてくださいね。
やりたいことを書いただけのコードが正ではありません、
それをビルドした成果物であるアプリケーションが正です。

2023-01-30 05:02 UTC, kitazawasyogo commented on Bowling.Test/BowlingTest.vb
> +    <Test()> Public Sub 二投目に九ピン倒した段階のスコアを計算()
> [Q] なんで同じようなこと2回書いてあるんですか？

すみません。[Q]の内容の理解が出来ていません。

コミットコメントの内容が同じようなことを2回言っているという事でしょうか。

2023-01-30 05:08 UTC, nabemasamasa reviewed
Done

2023-01-30 05:17 UTC, nabemasamasa commented on Bowling/Bowling.vb
> +    Private scoreList As New List(Of Integer)
このコミットには足りない差分がある……。
ここしか差分がないということは、どこも参照していないという事……。

2023-01-30 05:18 UTC, Takatatsu9 commented on Bowling/Bowling.vb
> +    Private scoreList As New List(Of Integer)
C#だったら即死だった

2023-01-30 05:20 UTC, Takatatsu9 commented on Bowling.Test/BowlingTest.vb
> +    <Test()> Public Sub 二投目に九ピン倒した段階のスコアを計算()
対象のコミットのコメントに同じようなことが2回書いてあることを指しています。

2023-01-30 05:27 UTC, kitazawasyogo commented on Bowling.Test/BowlingTest.vb
> +    <Test()> Public Sub 二投目に九ピン倒した段階のスコアを計算()
コメントありがとうございます。理解出来ました。

`前のテスト結果を残さず新しいテストをする為、変更`だけでよろしいでしょうか。
なぜ（Why）修正したのかを簡潔に書き修正内容は細かく書かないようにいたします。

2023-01-30 05:59 UTC, Takatatsu9 commented on Bowling.Test/BowlingTest.vb
> +    <Test()> Public Sub 二投目に九ピン倒した段階のスコアを計算()
その様子だと全く理解できていないようですね。
![image](https://user-images.githubusercontent.com/50448373/215398673-2b8ae6fa-4889-4162-8f26-87e92b483202.png)
なんで同じようなこと2回書いてあるんですか？

2023-01-30 06:14 UTC, kitazawasyogo commented on Bowling.Test/BowlingTest.vb
> +    <Test()> Public Sub 二投目に九ピン倒した段階のスコアを計算()
コミットをまとめた後にコミットコメントの修正を行ったからだと思います。
https://github.com/kitazawasyogo/bowling/pull/10#discussion_r1090117422

コミットをまとめた時にコミットコメントの修正を行えばよかったのですが、忘れてしまいました。

2023-01-30 06:19 UTC, Takatatsu9 commented on Bowling.Test/BowlingTest.vb
> +    <Test()> Public Sub 二投目に九ピン倒した段階のスコアを計算()
そうですか。
おそらくsquashでコミット整理するとこうなります。fixupだと頭のコミットコメントだけになります。

2023-01-30 06:26 UTC, kitazawasyogo commented on Bowling.Test/BowlingTest.vb
> +    <Test()> Public Sub 二投目に九ピン倒した段階のスコアを計算()
squashでコミットコメントの修正を行いました。

2023-01-30 06:35 UTC, Takatatsu9 commented on Bowling.Test/BowlingTest.vb
> +    <Test()> Public Sub 二投目に九ピン倒した段階のスコアを計算()
やっぱり。次からは2つ以上のコミットをくっつけるときはfixupを使ってみてください。

ちなみに、直したいコミットに対する修正コミットに変更後のコメントとかを
メモったときはsquashのほうが便利です。

2023-01-30 06:59 UTC, kitazawasyogo commented on Bowling/Bowling.vb
> +    Private scoreList As New List(Of Integer)
コミットをまとめた後　https://github.com/kitazawasyogo/bowling/commit/f79f80044d9708c16d431252c528572eb478a405
をコミットし、その後に間違えたrebaseを取り消すために git reset --hard HEAD@{2}を実行してしまったからだと思います。

コミット整理後、追加の追加で差分の修正をPushするようにします。

2023-01-30 07:01 UTC, kitazawasyogo commented
コミット整理を行い強制プッシュしました。[変更点](https://github.com/kitazawasyogo/bowling/compare/f79f80044d9708c16d431252c528572eb478a405..b5e4c7a795fb0073b542c0ade38c3d8f97fa711c)はございません。

2023-01-30 07:04 UTC, Takatatsu9 approved these changes

2023-01-30 07:07 UTC, nabemasamasa commented on Bowling/Bowling.vb
> +    Private scoreList As New List(Of Integer)
はい、お願いします。
(コミット整理後、まだ残ってる事も確認済み。「差分の修正」のPusu待ち……)

2023-01-30 07:32 UTC, nabemasamasa reviewed
Done!

2023-01-30 07:33 UTC, nabemasamasa approved these changes

2023-01-30 07:56 UTC, Takatatsu9 commented
なんでコミット整理だけでコンフリクト起きてるんだ？なんで違うPRの内容が現れてるんだ？

2023-01-30 08:13 UTC, kitazawasyogo commented
コミット整理時に不要なコミットを含めてしまいました修正します。
GitExtensions確認怠ってしまいました。

2023-01-30 08:19 UTC, kitazawasyogo commented
コミット整理し強制プッシュしました。[変更点](https://github.com/kitazawasyogo/bowling/compare/46c6e9b490999ad917f4c59c3d717828f4af2736..0aa892867e0d4e0452837529e3fb552886756190)はございません。
マージいたします。

2023-01-30 23:15 UTC, merged

2023-01-30 23:57 UTC, nabemasamasa reviewed
Done