引数の配列の合計値を返すメソッドの追加
kitazawasyogo/bowling pull request #4
Opened 2023-01-20 01:58 UTC by kitazawasyogo

@nabemasamasa　@Takatatsu9
 
 引数の配列の合計値を返すメソッドを追加しました。
 不足している部分やより良い書き方があれば教えていただきたいです。
お忙しいところ恐れ入りますがレビューお願いいたします。

2023-01-20 02:33 UTC, nabemasamasa requested changes, later dismissed
NG、Issueの内容を読み返してください。

2023-01-20 02:33 UTC, nabemasamasa commented on Bowling.Test/BowlingTest.vb
>      <Test()> Public Sub NUnitでのサンプルコード()
???
[Q] なんでメソッド新しく作らないんです？
「テストを作成せよ」って書いてあって「既存のテストを修正せよ」とは書いてなかったと思うのですが。

2023-01-20 02:33 UTC, nabemasamasa commented on Bowling.Test/BowlingTest.vb
> +        Dim actual As Integer = Bowling.SumPinsValue(pinsArray)
[Q] Issueの説明読みました？メソッド名の指定ありませんでしたか？

2023-01-20 02:33 UTC, nabemasamasa commented on Bowling/Bowling.vb
> +        Return (totalValue)
[IMO] これなら直接`pins.Sum()`を返しちゃう。
コードがシンプルだから、「変数を経由することで変数名を使って意味を表現する」テクニックを使用する必要もないしね。

2023-01-20 02:33 UTC, nabemasamasa commented on Bowling.Test/BowlingTest.vb
> +    ''' </summary>
テストクラス、テストメソッドの場合、コメントつけなくていいです。
クラス名でどのクラスのテストかどうか、わかりますし、
テストメソッド名で何を検証しているテストなのかどうか、わかります。

2023-01-20 02:43 UTC, kitazawasyogo commented on Bowling.Test/BowlingTest.vb
>      <Test()> Public Sub NUnitでのサンプルコード()
Issueの説明を正しく理解できていませんでした。

間違えて変更を加えてしまった既存のテストは元の状態に戻し、新しくテストを作成いたします。

2023-01-20 02:44 UTC, kitazawasyogo commented on Bowling.Test/BowlingTest.vb
> +        Dim actual As Integer = Bowling.SumPinsValue(pinsArray)
Issueの説明を正しく理解できていませんでした。

指定していただいたメソッドに修正いたします。
今回はメソッド名と一致しないコメントになってしまうのですが大丈夫でしょうか。

2023-01-20 02:48 UTC, kitazawasyogo commented
Issueの説明を正しく理解できておらず申し訳ございません。

次回以降Issueについて不明点や理解できていない部分がありましたらIssueのコメントもしくはremottyのチャットや画面共有で質問し確認を行ってから作業致します。

2023-01-20 03:10 UTC, nabemasamasa commented on Bowling.Test/BowlingTest.vb
> +        Dim actual As Integer = Bowling.SumPinsValue(pinsArray)
会話して理解しました。
Bowling.Scoreにすると、Scoreというメソッド名に対して、XMLコメントがメソッド名に一致しないコメントになってしまうのは大丈夫か、という質問でした。
ボーリングというゲームの中で、倒したピンの数に対して得点を計算するメソッドを想定しているので、こちらも修正をお願いしました。
併せて、Summary以外のコメントも埋めるようお願いしました。

2023-01-20 04:44 UTC, kitazawasyogo commented
レビューありがとうございます。

ご指摘頂いた部分の修正を行いましたのでレビューお願いいたします。

2023-01-20 05:56 UTC, nabemasamasa reviewed
done

2023-01-20 05:56 UTC, nabemasamasa commented on Bowling/Bowling.vb
> +        Return (pins.Sum())
[Q] ちなみに、`pins.Sum()`をカッコで囲ってるのって、理由がありますか？

2023-01-20 05:56 UTC, nabemasamasa commented on Bowling/Bowling.vb
> +    ''' <returns>得点の合計値</returns>
[imo] `fixup`すると思うので直さなくていいんですが、私ならメソッド名の修正とSummaryコメントの修正は一緒のコミットでやります。
`SumPinsValue`というメソッドを表現するコメントが「引数の配列の合計値を返す」で、`Score`が「点数を返す」で、一体となっていると思うからです。
その理由から、引数や戻り値のコメントが足りないのはそれはそれで別コミットで良かったと思います。(まぁ、その「足りないコメント追加」コミットもFixupすると思うんですが)

2023-01-20 05:56 UTC, nabemasamasa commented on Bowling/Bowling.vb
> +    ''' <param name="pins">得点の入った配列</param>
[Q] `pins`って得点の配列って言いましたっけ…？

例えば「スコア計算時に倒したピンの数が7だったらラッキーセブンで2倍の得点で計算して」って要望が来たら、スコア計算するこのメソッドの引数に7を2倍にしてある、既に計算済みの状態で配列を渡すんですか？得点の計算してなくありませんか？

2023-01-20 05:56 UTC, nabemasamasa commented on Bowling/Bowling.vb
> +    ''' 点数を返すメソッド
確かにXMLコメントはクラスの使い方を知るのにとても良い情報元になりますが、
コメントの末尾の「メソッド」までは見ればわかるのでいらないです。

一例ですが、これは変数`Hoge`と`DoSome`メソッドと`Fuga`プロパティを持つクラスの入力候補表示なんですが、`DoSome`がメソッドであることはアイコンでもわかりますし、選択した時表示されるコメントにも`Sub`って書いてあるのでそれでわかります。

![image](https://user-images.githubusercontent.com/20126608/213623736-d52523b1-d907-46cc-b691-388c8991cbc1.png)

2023-01-20 05:57 UTC, nabemasamasa commented on Bowling.Test/BowlingTest.vb
> +    ''' </summary>
0192220463b11306ef88aea84104d08ad53ade38 で解決を確認した

2023-01-20 05:58 UTC, nabemasamasa commented on Bowling/Bowling.vb
> +        Return (totalValue)
82cf448fae2ce680cabfced52419e1868f2ceaa7 で解決は確認した

2023-01-20 05:59 UTC, nabemasamasa commented on Bowling/Bowling.vb
> +        Return (pins.Sum())
忘れてた、「戻り値の設定方法の改修」ってコミットコメント、Whyで書いてないです。
[Q] なんでなんでしたっけ？

2023-01-20 06:01 UTC, nabemasamasa commented on Bowling.Test/BowlingTest.vb
>      <Test()> Public Sub NUnitでのサンプルコード()
0192220463b11306ef88aea84104d08ad53ade38 で解決を確認したのでResolve convesation。

2023-01-20 06:02 UTC, nabemasamasa commented on Bowling.Test/BowlingTest.vb
> +        Dim actual As Integer = Bowling.SumPinsValue(pinsArray)
af378ae6224e4ea2b7823e837db9e6672a1a8c42 で解決を確認した。
未解決の指摘がわかりやすいようにこれもResolve conversationで畳む。

2023-01-20 06:17 UTC, kitazawasyogo commented on Bowling/Bowling.vb
> +        Return (pins.Sum())
理由はありません。

不要な括弧を消し、`Return pins.Sum()`に修正いたします。

2023-01-20 06:24 UTC, kitazawasyogo commented on Bowling/Bowling.vb
> +        Return (pins.Sum())
コードがシンプルなので、「変数を経由することで変数名を使って意味を表現する」必要がないからです。

`変数名を使って意味を表現する必要がない為、戻り値の設定方法の改修`
というコミットコメントに修正したいと思います。

2023-01-20 06:38 UTC, kitazawasyogo commented on Bowling/Bowling.vb
> +    ''' <param name="pins">得点の入った配列</param>
得点の配列とは言っていませんでした。

`倒したピンの数の配列`というコメントに修正したいと思います。

2023-01-20 06:47 UTC, kitazawasyogo commented on Bowling/Bowling.vb
> +    ''' 点数を返すメソッド
不要な「メソッド」を削除し`点数を返す`という適切なコメントに修正いたします。

2023-01-20 07:20 UTC, kitazawasyogo commented
ご指摘頂いた部分の修正とコミットコメントを修正し強制プッシュしました。[変更点](https://github.com/kitazawasyogo/bowling/compare/ed340bac580820e9c9b5babcdc6d9f155b0bce2f..a0b544e028eafe5773fd02317b0bb42e7baa54f4)はございません。
お忙しいところ恐れ入りますがレビューお願いいたします。

分かりずらくなってしまい申し訳ございません。コミットコメントの修正を先に行うべきでした。

2023-01-22 23:28 UTC, nabemasamasa reviewed
Done

2023-01-23 00:50 UTC, Takatatsu9 reviewed
Done

2023-01-23 01:13 UTC, kitazawasyogo commented
コミットの整理を行い強制プッシュしました。[変更点](https://github.com/kitazawasyogo/bowling/compare/a0b544e028eafe5773fd02317b0bb42e7baa54f4..e9526fe55effc2d96a478352176f43a45f7cd674)はございません。

マージいたします。

2023-01-23 01:14 UTC, merged