Scoreの引数の配列の長さが異なる場合、引数例外を投げる処理の追加
kitazawasyogo/bowling pull request #5
Opened 2023-01-20 05:59 UTC by kitazawasyogo

@nabemasamasa　@Takatatsu9

**Scoreの引数の配列の長さが異なる場合、引数例外を投げる処理の追加を行いました。**

不足している部分やより良い書き方があれば教えていただきたいです。
お忙しいところ恐れ入りますがレビューお願いいたします。

2023-01-20 06:00 UTC, kitazawasyogo commented
不要なコミットを含めてしまいましたので修正いたします。

2023-01-20 08:03 UTC, nabemasamasa commented
待ってほしいなら、解決までCloseしてはいかが？

2023-01-20 08:03 UTC, nabemasamasa commented
あと、RunTestしてFailedがないこと確認してからPushしてください。
(自動テストできる仕組みに今なってないので申し訳ないですが…)

2023-01-23 00:31 UTC, kitazawasyogo commented
[5709942](https://github.com/kitazawasyogo/bowling/pull/5/commits/57099422d0155f02ed11a315e12acd3cf893497f)こちらのコミットのレビューお願いいたします。

[82cf448](https://github.com/kitazawasyogo/bowling/pull/5/commits/82cf448fae2ce680cabfced52419e1868f2ceaa7)ここまでのコミットは`session1 #1`の内容なのでレビュー結構です。後でrebaseして消えます。
`引数の配列の合計値を返すメソッドの追加 #4`のPRのマージ出来ましたらコミット整理を行いたいと思います。

2023-01-23 00:35 UTC, nabemasamasa commented
別ブランチを基点にしたブランチの場合、PR立てる際にCompareのbaseをその「別ブランチ」にすれば、そのブランチのコミット達は表示されなくなります。
PR立てた後も修正できて、PRタイトルの隣、Editをクリックして、baseをmasterからそのブランチに変えて、SaveすればOKです。

2023-01-23 00:49 UTC, nabemasamasa commented
でも、最新のfeat/bowling-score基点に出来てないのか、Conflictが発生してる。
`戻り値～～～`のコミット、どこかで見たな……

2023-01-23 01:08 UTC, Takatatsu9 requested changes
Done

2023-01-23 01:08 UTC, Takatatsu9 commented on Bowling.Test/BowlingTest.vb
> +    <Test()> Public Sub 配列の長さが少ない場合例外を投げるテスト()
[nits] `配列の長さが少ない場合例外`だけでいいですよ。
「こういう操作をしたらこういう挙動になる」みたいな書式で十分伝わりますので。
（一応今のままでも通じるし別に今直さなくてもいい）

2023-01-23 01:08 UTC, Takatatsu9 commented on Bowling.Test/BowlingTest.vb
> +            Assert.That(actual, [Is].EqualTo(ex))
[MUST] これどう見ても動くはずがないテストです。
このテストで何をやっているのか説明すると、何もしないで終了、となっています。
`Try 〜 Catch`は`Try`内で書かれた処理を行い、`Catch`で指定した例外が起きた場合
`Catch`内に書かれた処理を実行する、ということをやるので
`Try`に何も書かれていない＝何もしない→何も起きないので正常終了、となります。

2023-01-23 01:08 UTC, Takatatsu9 commented on Bowling/Bowling.vb
> +        If Not pins.Length = 21 Then
[IMO] `Not aaa = bbb`は`aaa <> bbb`でもOK。`<>`は一致しないって意味の演算子。

2023-01-23 01:08 UTC, Takatatsu9 commented on Bowling.Test/BowlingTest.vb
> +
[IMO] 例外のテストをするなら、`Try`内の最後の行に`Assert.Fail()`を書くといいです。
こうすると、例外が起きることを期待するテストなのに何も起きなかった場合にテストが落ちてくれます。

2023-01-23 01:29 UTC, nabemasamasa commented on Bowling.Test/BowlingTest.vb
> +            Assert.That(actual, [Is].EqualTo(ex))
@kitazawasyogo  [knowledge/xUnit.md](https://github.com/daniel-software-tokyo/knowledge/blob/master/xUnit.md#xunit)をもう一度読み返してください。特に、下の内容は読んでください。
[knowledge/xUnit.md#例外のテスト](https://github.com/daniel-software-tokyo/knowledge/blob/master/xUnit.md#%E4%BE%8B%E5%A4%96%E3%81%AE%E3%83%86%E3%82%B9%E3%83%88)

(xUnit.md読んでは金曜の朝会の困り事「テストの作り方がわからない」の解決の為、説明した時にknowledgeのxUnit.md開いてもらって、それ読んでって言ってた気もするんだけどな……)

2023-01-23 04:56 UTC, kitazawasyogo commented
レビューありがとうございます。

ご指摘頂いた部分の修正を行いPushしました。
お忙しいところ恐れ入りますがレビューお願いいたします。

2023-01-23 05:00 UTC, kitazawasyogo commented on Bowling.Test/BowlingTest.vb
> +            Assert.That(actual, [Is].EqualTo(ex))
レビューありがとうございます。
Knowledgeを読み返しました。

こちらのコメントでご指摘頂いた部分を修正したコミットは[63e3f54](https://github.com/kitazawasyogo/bowling/pull/5/commits/63e3f54b27621095e243bac1aab6c4d2d6cb2514)こちらです。　

2023-01-23 06:50 UTC, Takatatsu9 reviewed
Done

2023-01-23 06:50 UTC, Takatatsu9 approved these changes

2023-01-23 06:54 UTC, nabemasamasa reviewed
done

2023-01-23 06:56 UTC, nabemasamasa approved these changes

2023-01-23 07:31 UTC, kitazawasyogo commented
お忙しい中レビューありがとうございます。
コミット整理を行い強制プッシュしました。[変更点](https://github.com/kitazawasyogo/bowling/compare/1d57e7a6cc7f20a44044ab44c37d7aec3dbdc08d..e293c795142e55008a33fe45872e29f1319f4c2a)はございません。

マージいたします。

2023-01-23 07:50 UTC, merged

2023-01-23 07:55 UTC, nabemasamasa commented
NG。
masterの内容をこのPRのブランチへマージするコミットで、テストコケてます。
最優先でテストが動くようにしてください。
https://github.com/kitazawasyogo/bowling/actions/runs/3984336402/jobs/6830444322

2023-01-23 08:03 UTC, nabemasamasa commented
こういうことがあるので、Push前のRunTest確認や、conflict解決後のRunTests確認はしないといけないです。
人の手でconflict解決する以上、コンパイルエラーも、デグレも混入しうる……。
https://github.com/kitazawasyogo/bowling/pull/5#issuecomment-1398038427

2023-01-23 08:08 UTC, Takatatsu9 commented
前言ったMergeする判断基準に、「テストが ✅ になっている」も追加してください。